name: Build Flet Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Versão altamente estável com Flet

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x' # Trava em uma versão estável do Flutter do mercado

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet pillow

      - name: Pre-configure Flet Environment
        run: |
          # Garante que o diretório build exista de forma limpa antes do empacotamento
          mkdir -p build/apk

      - name: Build APK
        run: |
          flet build apk --verbose
